export const education = [
    {
        id: 1,
        degree: "Bachelor of Computer Applications",
        field: "Computer Applications",
        institution:
            "Abeda Inamdar Senior College of Arts, Science and Commerce",
        location: "Camp, Pune, Maharashtra, India",
        startYear: "2022",
        endYear: "2025",
        cgpa: "9.114",
        percentage: "85.9",
        grade: "A+",
        relevantCourses: [
            "Data Structures and Algorithms",
            "Web Development",
            "Database Management",
            "Software Engineering",
            "Operating Systems",
            "Computer Networks",
            "Object-Oriented Programming",
            "Mobile Application Development",
            "Cloud Computing",
            "Data Science",
            "Data Mining",
        ],
    },
    {
        id: 2,
        degree: "Diploma in Computer Applications",
        field: "Computer Applications",
        institution: "Deccan Muslim Institute",
        location: "Camp, Pune, Maharashtra, India",
        startYear: "2021",
        endYear: "2022",
        percentage: "75",
        grade: "B",
        relevantCourses: [
            "Basic Computer",
            "Basic Programming ",
            "Computer Hardware",
            "Computer Networking",
            "Computer Graphics",
            "Microsoft Office",
            "Accounting",
        ],
    },
    {
        id: 3,
        degree: "Higher Secondary Certificate (12th)",
        field: "Science",
        institution: "Aki's Poona College of Arts, Science and Commerce",
        location: "Camp, Pune, Maharashtra, India",
        startYear: "2020",
        endYear: "2021",
        percentage: "85.5",
        grade: "A",
        relevantCourses: [
            "Urdu",
            "English",
            "Mathematics",
            "Physics",
            "Chemistry",
            "Biology",
        ],
    },
    {
        id: 4,
        degree: "Secondary School Certificate (10th)",
        field: "General",
        institution: "Dr. W. R. Khan High School",
        location: "Hadapsar, Pune, Maharashtra, India",
        startYear: "2018",
        endYear: "2019",
        percentage: "81.2",
        grade: "A",
        relevantCourses: [
            "Urdu",
            "English",
            "Marathi",
            "Arabic",
            "Mathematics",
            "Science",
            "Social Science",
        ],
    },
];
