export const projects = {
    major: [
        {
            id: "1",
            title: "Collaborative Todo App",
            description:
                "A modern, real-time collaborative task management application built with the MERN stack. Teams can manage tasks together with live updates, user assignments, drag & drop functionality, and comprehensive activity tracking.",
            technologies: [
                "React",
                "Node.js",
                "Express.js",
                "MongoDB",
                "Socket.io",
                "Tailwind CSS",
                "JWT",
                "bcryptjs",
                "Axios",
                "Vite",
            ],
            role: "Full Stack Developer",
            duration: {
                start: "2024-10",
                end: "2024-12",
            },
            highlights: [
                "Real-time collaboration with Socket.io for live task updates",
                "Drag & drop interface for intuitive task management",
                "User authentication with JWT and role-based access",
                "Activity logging with comprehensive audit trail",
                "Responsive design with modern UI/UX",
            ],
            github: "https://github.com/Khanr7433/collab-todo-app",
            liveDemo: "https://collab-todo-app.vercel.app/",
            category: "Web Development",
        },
        {
            id: "2",
            title: "Project Approval System",
            description:
                "The Project Approval System is a web application designed to streamline the process of project approvals.",
            technologies: [
                "React",
                "Tailwind CSS",
                "Node.js",
                "Express.js",
                "MongoDB",
                "jwt",
                "bcryptjs",
                "axios",
                "multer",
                "cloudinary",
                "nodemailer",
                "react-router-dom",
                "react-toastify",
            ],
            role: "Full Stack Developer",
            duration: {
                start: "2024-12",
                end: "2025-02",
            },
            highlights: [
                "Implemented responsive design",
                "Integrated with various APIs",
                "Implemented role-based access for students and faculty to submit, review, and approve project proposals",
                "Deployed the application for local testing using GitHub and Vercel",
            ],
            github: "https://github.com/Khanr7433/Project_approval_system",
            liveDemo: "",
            category: "Web Development",
        },
        {
            id: "3",
            title: "E-auction System",
            description:
                "The E-Auction System is a web application designed to streamline the process of auctioning products.",
            technologies: [
                "html",
                "css",
                "javascript",
                "tailwind css",
                "python",
                "django",
                "sqlite3",
                "postgresql",
            ],
            role: "Full Stack Developer",
            duration: {
                start: "2024-08",
                end: "2024-09",
            },
            highlights: [
                "Implemented responsive design",
                "Integrated with various APIs",
                "Enabled real-time bidding functionality with automatic auction timers and winner detection",
                "Applied user authentication and admin panel controls for managing product listings andusers",
                "Deployed the application for local testing using GitHub and Vercel",
            ],
            github: "https://github.com/Khanr7433/E_Auction-system-using-django",
            liveDemo: "",
            category: "Web Development",
        },
        {
            id: "4",
            title: "Next.js Authentication System",
            description:
                "A comprehensive authentication system built with Next.js 15, featuring user registration, login, email verification, password reset, and profile management.",
            technologies: [
                "Next.js",
                "TypeScript",
                "Tailwind CSS",
                "MongoDB",
                "Mongoose",
                "JWT",
                "bcryptjs",
                "Nodemailer",
            ],
            role: "Full Stack Developer",
            duration: {
                start: "2024-11",
                end: "2024-12",
            },
            highlights: [
                "Complete authentication flow with email verification",
                "Password reset functionality with secure tokens",
                "Protected routes with middleware",
                "Profile management with image uploads",
                "Modern TypeScript implementation",
            ],
            github: "https://github.com/Khanr7433/nextjs-auth-system",
            liveDemo: "https://nextjs-auth-system-phi.vercel.app",
            category: "Web Development",
        },
        {
            id: "5",
            title: "Translate App - React",
            description:
                "A modern React translation application with Tailwind CSS styling and Vite build tool. Support for 21 languages with text-to-speech and translation history features.",
            technologies: [
                "React",
                "Tailwind CSS",
                "Vite",
                "Axios",
                "MyMemory Translation API",
                "JavaScript",
            ],
            role: "Frontend Developer",
            duration: {
                start: "2024-06",
                end: "2024-07",
            },
            highlights: [
                "Multi-language translation support for 21 languages",
                "Text-to-speech functionality using browser speech synthesis",
                "Translation history with local storage",
                "Language swapping and copy-to-clipboard features",
                "Modern Google-inspired UI design",
            ],
            github: "https://github.com/Khanr7433/translate-app-react",
            liveDemo: "https://translate-app-react.vercel.app",
            category: "Web Development",
        },
    ],
    minor: [
        {
            id: "6",
            title: "Personal Dashboard",
            description:
                "A modern dashboard built with Next.js and Tailwind CSS to showcase personal portfolio and track various metrics",
            technologies: ["Next.js", "React", "Tailwind CSS", "JavaScript"],
            role: "Full Stack Developer",
            duration: {
                start: "2025-05-20",
                end: "2025-05-25",
            },
            highlights: [
                "Implemented responsive design",
                "Created reusable components",
                "Integrated with various APIs",
            ],
            github: "https://github.com/Khanr7433/personal-dashboard",
            liveDemo: "https://personal-dashboard-psi-ivory.vercel.app/",
            category: "Web Development",
        },
        {
            id: "7",
            title: "Todo App - Modern Task Manager",
            description:
                "A beautiful and modern Todo application built with React, Vite, and Tailwind CSS. Features a stunning blue gradient design with smooth animations and intuitive user interface.",
            technologies: [
                "React",
                "Vite",
                "Tailwind CSS",
                "Context API",
                "Local Storage API",
                "JavaScript",
            ],
            role: "Frontend Developer",
            duration: {
                start: "2024-05",
                end: "2024-06",
            },
            highlights: [
                "Modern glassmorphism UI with blue gradient theme",
                "Task statistics with visual progress indicators",
                "Context API for state management",
                "Local storage for data persistence",
                "Responsive design with smooth animations",
            ],
            github: "https://github.com/Khanr7433/todo-app",
            liveDemo: "https://todo-app-psi-sandy-14.vercel.app/",
            category: "Web Development",
        },
        {
            id: "8",
            title: "Currency Converter",
            description:
                "A modern currency converter application with real-time exchange rates and intuitive user interface.",
            technologies: [
                "React",
                "Vite",
                "Tailwind CSS",
                "JavaScript",
                "Currency API",
            ],
            role: "Frontend Developer",
            duration: {
                start: "2024-04",
                end: "2024-05",
            },
            highlights: [
                "Real-time currency exchange rates",
                "Support for multiple currencies",
                "Responsive design with modern UI",
                "Fast performance with Vite",
                "Clean and intuitive user interface",
            ],
            github: "https://github.com/Khanr7433/currency-converter",
            liveDemo: "https://currency-converter-zeta-beryl.vercel.app",
            category: "Web Development",
        },
        {
            id: "9",
            title: "Password Generator",
            description:
                "A secure password generator application with customizable options for creating strong passwords.",
            technologies: ["React", "Vite", "Tailwind CSS", "JavaScript"],
            role: "Frontend Developer",
            duration: {
                start: "2024-03",
                end: "2024-04",
            },
            highlights: [
                "Customizable password length and character sets",
                "Copy to clipboard functionality",
                "Secure random password generation",
                "Modern responsive design",
                "User-friendly interface",
            ],
            github: "https://github.com/Khanr7433/password-generator",
            liveDemo: "(https://password-generator-three-blue-53.vercel.app",
            category: "Web Development",
        },
    ],
};
